---
title: "Project Notebook"
output:
  prettydoc::html_pretty:
    highlight: github
    toc: yes
    toc_depth: 2
    theme: lumen
  '# prettydoc::html_pretty': default
---

```{css echo=FALSE}
@import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap');
code{
  font-family: 'Fira Code'!important;
}
```

# Requirements 

```{r message=FALSE, warning=FALSE}
if (!require(tree))
  install.packages('tree')
library(tree)

if (!require(randomForest))
  install.packages("randomForest")
library(randomForest)

if (!require(rpart))
  install.packages("rpart")
library(rpart)

if (!require(rpart.plot))
  install.packages("rpart.plot")
library(rpart.plot)
```

# Pre-process Data

## Read data
```{r}
data <-
  read.csv('ObesityDataSet.csv',
           na.strings = '?',
           stringsAsFactors = T)
data <- na.omit(data)
```

## rename columns 
```{r paged.print=TRUE}
colnames(data)[6] <- 'eats_high_calor_food'
colnames(data)[7] <- 'eats_veggies'
colnames(data)[8] <- 'num_meals'
colnames(data)[9] <- 'eats_snacks'
colnames(data)[11] <- 'drinks_water'
colnames(data)[12] <- 'counts_calories'
colnames(data)[13] <- 'exercises_often'
colnames(data)[14] <- 'time_using_tech'
colnames(data)[15] <- 'drinks_alcohol'
colnames(data)[16] <- 'method_trans'
colnames(data)[17] <- 'weight_category'

head(data)
```

## split sample and test
```{r}
set.seed(1)

train <- sample(1:nrow(data), nrow(data) / 2)
test <- data[-train, ]
```

# Decision Tree

## Plant a tree
```{r}
data.tree <- tree(weight_category ~ ., data = data)
tree <- rpart(weight_category ~ ., data = data)
summary(data.tree)
```

```{r}
rpart.plot(tree, box.palette="RdBu", shadow.col="gray", nn=TRUE)
plot(data.tree)
# text(data.tree, pretty = 0)
```

### evaluate tree
```{r}
data.tree <- tree(weight_category ~ ., data = data, subset = train)
data.tree.pred = predict(data.tree, test, type = "class")
```


```{r}
table(data.tree.pred, test$weight_category)
mean(data.tree.pred == test$weight_category)
```

## cross validation
```{r}
cv.data <- cv.tree(data.tree, FUN = prune.misclass)
names(cv.data)
plot(cv.data)
cv.data
```

```{r}
prune.data <- prune.misclass(data.tree, best = 9)
plot(prune.data)
text(prune.data, pretty = 0)
```

```{r}
prune.data.pred <- predict(prune.data, test, type = "class")
table(prune.data.pred, test$weight_category)
mean(prune.data.pred == test$weight_category)
```

```{r}
data.forest <- randomForest(
  weight_category ~ .,
  data = data,
  subset = train,
  ntree = 5000,
  importance = T
)
data.forest
plot(data.forest)
```

```{r}
data.forest <- randomForest(
  weight_category ~ .,
  data = data,
  subset = train,
  ntree = 5000,
  mtry = ncol(data) - 1,
  importance = T
)
data.forest
plot(data.forest)
```

```{r}
importance(data.forest)
varImpPlot(data.forest)
```

```{r}
data.forest.pred <- predict(data.forest, test, typr = "class")
table(data.forest.pred, test$weight_category)
mean(data.forest.pred == test$weight_category)
```

```{r warning=FALSE}
mtry.list <- c()
data.forest.final <- NULL
i <- 1
max <- 0
for (i in 1:ncol(data) - 1) {
  data.forest.dummy <- randomForest(
    weight_category ~ .,
    data = data,
    subset = train,
    ntree = 5000,
    mtry = i,
    importance = T
  )
  val <- predict(data.forest.dummy, test, typr = "class")
  score <- mean(val == test$weight_category)
  if (score >= max) {
    data.forest.final <- data.forest.dummy
    max <- score
  }
  mtry.list[i] <- score
}
```

```{r}
mtry.list
plot(mtry.list)
```

```{r}
data.forest.final
plot(data.forest.final)
```

```{r}
importance(data.forest.final)
varImpPlot(data.forest.final)
```

```{r}
data.forest.final.pred <- predict(data.forest.final, test, typr = "class")
table(data.forest.final.pred, test$weight_category)
mean(data.forest.final.pred == test$weight_category)
```

